[book]
title = "Workshop Handbook"
authors = ["CompClub"]
language = "en"
description = "A CompClub template for workshop handbooks built with mdBook."

[build]
build-dir = "book"

[output.html]
default-theme = "coal"
site-url = "/2026-winter-workshop-handbook/"
git-repository-url = "https://github.com/UNSW-CompClub/2026-winter-workshop-handbook"
additional-css = ["theme/custom.css"]
additional-js = ["theme/question.js", "theme/points.js", "reload-check.js"]

[preprocessor.callouts]
